### ISSUE TITLE
CloudFormation Template format error

### ISSUE THREAD

**Issue by M-swords** [getsocial-rnd/neo4j-aws-causal-cluster#4]
Hi @Trane9991 ! 

I'm trying to run your cloudformation stack. But get the error message:
`Template format error: Expected an object, received {"Fn::If":["EnableASGHook",{"AutoScalingRollingUpdate":{"MaxBatchSize":"1","MinInstancesInService":"2","PauseTime":"PT10M","WaitOnResourceSignals":"true"}},{"Ref":"AWS::NoValue"}]}`

I haven't modified the yaml file 
Any clue to why this is?

**Comment by taraspos** [comment]
Hey @M-swords, thanks for reporting this.

Could you please provide the set of parameters you used to create the stack?
I will need it to try to reproduce the error and fix it (probably some bad condition or typo).

Thanks!

**Comment by taraspos** [comment]
I think I fixed the issue. This commit [d8aa5ce8cf82e24fd65aee8ea923e526a39f680f](https://github.com/getsocial-rnd/neo4j-aws-causal-cluster/commit/d8aa5ce8cf82e24fd65aee8ea923e526a39f680f) should fix the problem.

Please try that out and let me know :) 

Thanks!

**Comment by M-swords** [comment]
Hi Thanks, that worked. 
I got another error which is related to my VPCs. Got the error
`One or more security groups in the launch template are not linked to the VPCs configured in the Auto Scaling group (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError`

My parameters are:
`

AcceptLicense | true | -
-- | -- | --
AdminPassword | **** | -
AdminUser | neo4j | -
AllowUpgrade | false | -
BackupDailyStoreForDays | 14 | -
BackupHourlyStoreForDays | 1 | -
BackupPath | - | -
CloudMapNamespaceID | - | -
CloudMapNamespaceName | neo4j.testing | -
ClusterInstanceType | t2.medium | -
DesiredCapacity | 3 | -
DockerECRARN | arn:aws:ecr:eu-central-1:111111111:repository/neo4j-docker | -
DockerImage | 111111111.dkr.ecr.eu-central-1.amazonaws.com/neo4j-docker:latest | -
EBSSize | 10 | -
EBSType | standard | -
ECSAMI | /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id | ami-111111111111
IsDrainSupported | false | -
KeyName | neo4j-ecs | -
Neo4jCoreSubdomain | core | -
Neo4jReplicasSubdomain | replica | -
NodeSecurityGroups | sg-XXXXXXX | -
ReadOnlyUser | neo4j_read | -
ReadOnlyUserPassword | **** | -
ReplicasCount | 0 | -
ReplicasInstanceType | t2.medium | -
ReplicasSubnetID | subnet-XXXXXXXXXX | -
SNSTopicArn | - | -
SlowQueryLog | disabled | -
SubnetID | subnet-111111,subnet-222222,subnet-333333 | -
VpcId | vpc-111222233333 | -

`

**Comment by M-swords** [comment]
Solved the security groups issues. Now struggling with Neo4jClusterECSservice

`service neo4j-ecs-stack-Neo4jClusterECSservice-1111111XX was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 1234-abcd-123-4532-1235 has insufficient memory available. For more information, see the Troubleshooting section.`

**Comment by taraspos** [comment]
🤔 
Didn't issue resolve itself after a couple of minutes? This error could happen because ECS trying to launch containers while instances aren't ready yet. Waiting for 2-3 minutes more usually resolves it.

Is instance type you used still t2.medium?

**Comment by M-swords** [comment]
I let it run for 10-15 minutes. Yea used t2.medium.
I'll try again

**Comment by taraspos** [comment]
Once you try to deploy it again and the issue happens to reproduce, please don't remove the cluster and let me know.

I may ask you to provide some information about the ECS cluster to resolve this.

**Comment by M-swords** [comment]
I deployed the cloudformation stack and it is stuck on trying to create the Neo4jClusterECSservice resource. 
In the event log of the Neo4jClusterECSservice it is repeating 
`service neo4j-stack-ecs-28-Neo4jClusterECSservice-111111111 was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 1111111-22222-3333-44444-4555asb has insufficient memory available. For more information, see the Troubleshooting section.`

**Comment by taraspos** [comment]
Got it.

Can you send me a screenshot of:
1. ECS Cluster page  *ECS Instances* tab.
2. ECS Cluster page *Tasks* tab with status *Running*
3. ECS Cluster page *Tasks* tab with status *Stopped*

**Comment by M-swords** [comment]
ECS instances:
![ECS_instances](https://user-images.githubusercontent.com/35534833/67679530-92c91c00-f989-11e9-9045-352b1661bd48.png)

Tasks Running:
![Tasks_running](https://user-images.githubusercontent.com/35534833/67679545-9c528400-f989-11e9-90a8-c79e9de5dcec.png)

Tasks Stopped
![Tasks_stopped](https://user-images.githubusercontent.com/35534833/67679558-a2e0fb80-f989-11e9-87c5-04dce19dd49c.png)

**Comment by taraspos** [comment]
The problem is that only one instance is running... need to be 3 at least.

Please check the AutoScaling group configuration. Are there any errors on the *Activity History* tab?

**Comment by taraspos** [comment]
Are the stack parameters the same as you shared before? Did you specify 3 subnets each in different availability zone?

**Comment by M-swords** [comment]
There are no errors in the activity history tab, we have three sucessful launches of EC2 instances which can been seen in EC2 service. 
Yes i used the same stack parameters. There are 4 subnets. The three specified for the Core servers are in different AZ and the fourth one is for the replica and is in one of the AZ of the cores.
There are 250 available IPV4 for each subnet

**Comment by taraspos** [comment]
Do your instances have internet access? (Internet Gateway or Nat Gateway attached to the subnets and Public IPs assigned to the instances)

This could be the reason, why one node became part of the ECS Cluster and others couldn't join because they can't communicate with the ECS service.

**Comment by M-swords** [comment]
Found that two of the subnets had the wrong route table assigned. The instances have public IPs assigned. After fixing the route tables i'm still waiting for the Neo4jClusterECSservice resource to complete.

**Comment by M-swords** [comment]
So the two missing ECS instances has been added:
![ECS_instances_v2](https://user-images.githubusercontent.com/35534833/67688971-f3148980-f99a-11e9-8f9e-134842ad9a9a.png)

But i'm getting a new error: 
`service neo4j-stack-ecs-28-Neo4jClusterECSservice-1111111111 was unable to place a task because no container instance met all of its requirements. The closest matching container-instance 11111-2222-3333-444-5555 is missing an attribute required by your task. For more information, see the Troubleshooting section.`

**Comment by taraspos** [comment]
Is it the same CloudFormation stack? Could be because of ECS throttling, since it was failing for a long time.

You can try to do [stop](https://github.com/getsocial-rnd/neo4j-aws-causal-cluster#stop-cluster) and [start](https://github.com/getsocial-rnd/neo4j-aws-causal-cluster#start-cluster), or create stack from scratch.

**Comment by M-swords** [comment]
Yes was the same CloudFormation stack. 
Rerunning the stack at the moment, one event during stack deployment was the Neo4jClusterECSservice which had a "Status reason" reading:
`Not able to add tag on resource AWS::ECS::Service. The new ARN and resource ID format must be enabled to add tags to the service`

Otherwise the stack was completed

**Comment by taraspos** [comment]
@M-swords does it mean that everything worked fine this time?

**Comment by M-swords** [comment]
Yes, got an issue with my custom image but that's a me problem.

Thank you a lot for your help!
